[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pyowasm"
version = "0.1.0"
authors = [
  { name="Your Name", email="your.email@example.com" },
]
description = "A Python WebAssembly tool/wrapper."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "biopython",
    "streamlit",
    "pandas",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/yourusername/pyowasm"
"Bug Tracker" = "https://github.com/yourusername/pyowasm/issues"

[tool.setuptools.packages.find]
where = ["src"]
